import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '../globals.css'
import ThemeRegistry from "@/theme/ThemeRegistry";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import {headers} from "next/headers";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    const headersList = headers();
    const hostname = headersList.get('host');

    return (
        <html lang="en">
        <body className={inter.className}>
        <GoogleAnalytics/>
        <ThemeRegistry options={{key: 'mui'}} hostname={hostname}>
            <NavBar/>

            {children}

            <Footer/>
        </ThemeRegistry>
        </body>
        </html>
    )
}
